### ISSUE TITLE
Centering the radius of the hopper

### ISSUE THREAD

**Issue by bigKuh** [APICO-Modders/Hoppers-Mod#2]
Both the drawn line and the working radius for the hopper's input and output range is not properly centred on the hopper.
I did some tweaking in the mod.lua and hopper.lua files and seemed to have fixed the issue.

In mod.lua, the drawn circle is off by one pixel. Line 83 needs to be changed from:

api_draw_circle(ox+8, oy+8, 32, "OUTLINE", true)

to

api_draw_circle(ox+7, oy+7, 32, "OUTLINE", true)

And in hopper.lua, there is no offset for the hopper's working circle. 
The "coord" variable defined on lines 60-63 needs to be changed from:

coord = {
    x = api_gp(menu_id, "obj_x"),
    y = api_gp(menu_id, "obj_y")
  }

to

coord = {
    x = api_gp(menu_id, "obj_x")+7,
    y = api_gp(menu_id, "obj_y")+7
  }

The change can be visualized in game below, with red (filled) and blue (unfilled) hives

Original
![(ox+8,oy+8),(x,y) at 32px default](https://user-images.githubusercontent.com/38109322/173268333-ef003d5b-f9cc-4060-a727-97e276c6cff3.png)

My fix
![(ox+7,oy+7),(x+7,y+7) at 32px](https://user-images.githubusercontent.com/38109322/173268360-fe054353-2444-4634-b008-c91a496692cd.png)

Hopefully this is the "right" way to fix this, I'm not familiar with Lua or that much programming in general but it seemed to do the trick. Otherwise excellent mod removes a ton of tedium from the game. Really looking forward to further versions and additions to the abilities of the hoppers!

-- Kyle

**Comment by ellraiser** [comment]
Fixed a million years later in 1.3.4! <3
